blank_issues_enabled: false
contact_links:
  - name: Azure Quantum technical support issues
    url: https://ms.portal.azure.com/#blade/Microsoft_Azure_Support/HelpAndSupportBlade/newsupportrequest
    about: Request technical support for Azure Quantum and optimization issues here. 
  - name: Azure Quantum technical Q&A
    url: https://docs.microsoft.com/en-us/answers/topics/azure-quantum.html
    about: Post a technical question to the Azure Quantum community.  
  - name: Azure Quantum feature requests
    url: https://feedback.azure.com/forums/932905-azure-quantum
    about: Use the feedback forum to request new features for Azure Quantum
  - name: Q# programming language issues
    url: https://github.com/microsoft/qsharp-language/issues/new/choose
    about: Post an issue about the Q# programming language here.
  - name: Quantum Development Kit (QDK) issues
    url: https://github.com/microsoft/qsharp-runtime/issues/new/choose
    about: Post an issue about the QDK runtime library here.
